SMSM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('maps/', include('maps.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    # path('delete/', views.delete, name='delete'),
    # path('update/', views.update, name='update'),
    # path('password/', views.change_password, name='change_password'),
    path('<int:user_pk>/', views.profile, name='profile'),
    # path('<int:user_pk>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views

app_name="movies"
urlpatterns = [
    # 전체 영화 목록
    path('', views.movie_index, name='movie_index'),
    # 영화 상세 페이지
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),

    # Review create
    path('<int:movie_pk>/create/', views.create, name='create'),
    # Review detail
    path('<int:movie_pk>/detail/<int:review_pk>', views.detail, name='detail'),
    # Review delete
    path('<int:movie_pk>/delete/<int:review_pk>', views.delete, name='delete'),
    # Review update
    path('<int:movie_pk>/update/<int:review_pk>', views.update, name='update'),
   
    # Comment create
    path('<int:movie_pk>/<int:review_pk>/comments/create', views.comments_create, name='comments_create'),
    # # Comment delete
    # path('<int:movie_pk>/<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    # # Review likes
    # path('<int:review_pk>/likes/', views.likes, name='likes'),
    # path('recommend/', views.recommend, name='recommend'),

]

movies/models.py
from django.db import models
from django.conf import settings

class Genre(models.Model):
    name = models.TextField()
    
class Movie(models.Model):
    title = models.TextField()
    poster_path = models.TextField()
    overview = models.TextField()
    genre_ids = models.ManyToManyField(Genre, related_name='movie_genre')
    popularity = models.FloatField()
    release_date = models.DateField()
    vote_average = models.IntegerField()
    original_title = models.TextField()

class Review(models.Model):
    movie_title = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    rank = models.IntegerField(blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

movies/forms.py
from django import forms
from django.forms import widgets
from .models import Movie, Review, Comment

class ReviewForm(forms.ModelForm):
    CHOICES= [
        (1, '★☆☆☆☆'),
        (2, '★★☆☆☆'),
        (3, '★★★☆☆'),
        (4, '★★★★☆'),
        (5, '★★★★★')
    ]
    rank = forms.IntegerField(
        label='별점',
        widget=forms.Select(
            choices = CHOICES,
            attrs={
                'style': 'width: 10rem;'
            }
        )
    )
    title = forms.CharField(
        label='글 제목',
        widget=forms.TextInput(
            attrs={'style': 'height: 2rem;' , 'class': 'form-control'}
        )
    )
    content = forms.CharField(
        label='글 내용',
        widget=forms.Textarea(
            attrs={'style': 'height: 10rem;', 'class': 'form-control'}
        )
    )
    class Meta:
        model = Review
        fields = ['title', 'rank', 'content',]


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={'style': 'height: 2rem;', 'class': 'form-control'}
        )
    )
    class Meta:
        model = Comment
        fields = ('content', )
    

movies/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_http_methods, require_GET, require_POST
from .models import Movie, Review
from .forms import ReviewForm, CommentForm

def movie_index(request):
    movies = Movie.objects.all()
    popular_movies = Movie.objects.all().order_by('vote_average')
    context = {
            'movies': movies,
            'popular_movies' : popular_movies,
        }
    return render(request, 'movies/movie_index.html', context)

# 영화 상세 페이지
# @require_GET
def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review_form = ReviewForm()
    reviews = movie.review_set.all()
    context = {
        'movie': movie,
        'review_form' : review_form,
        'reviews' : reviews
    }
    return render(request, 'movies/movie_detail.html', context)

# Review create

@require_POST
def create(request, movie_pk):
    form = ReviewForm(request.POST)
    movie = get_object_or_404(Movie, pk = movie_pk)
    if form.is_valid():
        review = form.save(commit=False)
        review.movie_title = movie
        review.user = request.user
        review.rank = 1
        review.save()
        return redirect('movies:movie_detail', movie.pk)


def detail(request, movie_pk, review_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review = get_object_or_404(Review, pk=review_pk)
    comments = review.comment_set.order_by('-pk')
    comment_form = CommentForm()
    context = {
        'movie' : movie,
        'review': review,
        'comment_form': comment_form,
        'comments': comments
    }
    return render(request, 'movies/review_detail.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def update(request, movie_pk, review_pk ):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review = get_object_or_404(Review, pk=review_pk)

    if request.user == review.user:
        if request.method =="POST":
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                form.save(commit=False)
                review.rank = 1
                form.save()
                return redirect('movies:movie_detail', movie.pk )
        else:
            form = ReviewForm(instance=review)
    # else:
    #     return redirect('movies:movie_index')
    context = {
        'form': form,
        'review' : review,   
    }
    return render(request, 'movies/update.html', context)

@require_POST
def delete(request, movie_pk ,review_pk):
    review = get_object_or_404(Review, pk = review_pk)
    if request.user.is_authenticated:
        if request.user == review.user:
            review.delete()
            return redirect('movies:movie_detail', movie_pk)
        return redirect('movies:movie_detail', movie_pk)

@require_POST
def comments_create(request, movie_pk ,review_pk ):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        review = get_object_or_404(Review, pk=review_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()
        return redirect('movies:detail', movie.pk, review.pk)
    return redirect('accounts:login')
# movies/views.py 아랫부분에 추가 (미완성)

# @login_required
# def recommend(request):
#     recommended_movies = Movie.objects.filter(genre_id=)[0:2]
#     context = {
#         'recommended_movies' : recommended_movies
#     }
#     return render(request, 'movies/recommend.html', context)

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="ui vertical stripe segment">
  <div class="ui middle aligned grid container">
  <div class="row">
  <div class="sixteen wide column">
    <div class="card text-center">
    <div class="card-header">
      <b>
      {{ movie.title }}
      </b>
    </div>
    <div class="card-body">
      <p class="card-text">{{ movie.overview }}</p>
      <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="">
    </div>
    <div class="card-footer text-muted">
      {{ movie.vote_average }}
    </div>
  </div>
  </div>
  </div>
</div>
</div>

<div class="container my-4">
  <div class="ui form">
    <div class="field">
      <label class="text-light">Review</label>
       <form action="{% url 'movies:create' movie.pk %}" method ='POST'> 
            {% csrf_token %}
            {{ review_form.as_p }}
            <div>
              <button class="ui blue labeled submit icon button" type="submit"> 
              <i class="icon edit" ></i>Write Review </button> 
            </div>
        </form>
    </div>
  </div>
</div>
<div class="container">
  <table class="ui celled striped table">
    <thead>
      <tr><th colspan="3">
        Reviews
      </th>
    </tr></thead>
    <tbody>
      <tr>
      {% for review in reviews %}
        <td>
          <a class="ui image label" href="{% url 'accounts:profile' review.user_id%}">
          {% if review.user.gender == '불특정' %}
            <img src= {% static 'images/smile.jpg' %}>
            {{ review.user }} 
          {% elif review.user.gender == '남'  %}
            <img src= {% static 'images/man1.png' %}>
            {{ review.user }}
          {% elif review.user.gender == '여'  %}
            <img src= {% static 'images/woman3.png' %}>
            {{ review.user }}
          {% endif %}
        </a> 
        <a href=" {% url 'movies:detail' movie.pk review.pk  %}"> {{ review.title }} </a>
        </td>
        <td> {{ review.content }}</td>
        <td class="right aligned">{{ review.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

movies/templates/movies/movie_index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/movie_index.css' %}">
  <div class="ui text container">
      <h1 class="ui inverted header">
        Share Movie,<br>
        Share Moments
      </h1>
      <h2>Because we do care</h2>
      <div class="ui huge primary button">Join <i class="right arrow icon"></i></div>
    </div>
  </div>
  <div class='me-4 text-align-center'>
    <div class="ui middle aligned container">
      <video width="1500" height="1500" src="{% static 'videos/smile_1920.mp4' %}" autoplay></video>
    </div>
  </div>
  <div class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
      {% comment %} <div class="row">
        <div class="eight wide column">
          <h3 class="ui header">We Help Children in need</h3>
          <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
          <h3 class="ui header">We Make Bananas That Can Dance</h3>
          <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
        </div>
        <div class="six wide right floated column">
          <img src="#" class="ui large bordered rounded image">
        </div>
      </div> {% endcomment %}
      <div class="row">
        <div class="center aligned column">
          <a class="ui huge button">Check Them Out</a>
        </div>
      </div>
    </div>
  </div>

  <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        {% comment %} <div class="column">
          <h3>"What a Company"</h3>
          <p>That is what they all say about us</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <img src="#" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
          </p>
        </div> {% endcomment %}
      </div>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui text container">
      {% comment %} <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
      <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
      <a class="ui large button">Read More</a>
      <h4 class="ui horizontal header divider">
        <a href="#">Case Studies</a>
      </h4>
      <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
      <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
      <a class="ui large button">I'm Still Quite Interested</a> {% endcomment %}
    </div>
  </div>
    <h2 class="ui header justify-content-center">MOVIES</h2>
    <div class="ui four column grid">
      <div class="row justify-content-center movie-boxes">
      {% for movie in movies %}
        <div class="ui card column mx-2 my-4 captured">
        <div class="image">
          <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}">
        </div>
        <div class="content">
          <a class="header">{{ movie.title }}</a>
          <div class="meta">
            <span class="date">{{ movie.release_date }}</span>
          </div>
          <div class="description">
            {{ movie.overview|truncatechars:100 }}
          </div>
        </div>
        <div class="extra content">
          <a>
            <i class="star icon"></i>
            {{ movie.vote_average }}
          </a>
        </div>
        <div class="ui two bottom attached buttons">
          <a class="ui button">
            <i class="add icon"></i>Detail</a>
          <a class="ui primary button" href="{% url 'movies:movie_detail' movie.pk %}">
            <i class="play icon"></i>Watch</a>
        </div>
      </div>
      {% endfor %}
      </div>
    </div>
    
  <script src="{% static 'javascripts/movie_index.js' %}"></script>
{% endblock content %}

movies/templates/movies/recommend.html
{% extends 'base.html' %}

{% block content %}
  
{% endblock content %}

movies/templates/movies/review_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Review detail</h1>
   <h2> 영화제목 : {{ movie.title }} </h2>
   <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt=""> 
   <br>
   <h5> 내용: {{ review.content }}</h5>
   <div>
   </div>
  {% comment %} 수정 삭제 뒤로가기 {% endcomment %}
  <a href="{% url 'movies:update' movie.pk review.pk%}"  >수정</a>
  
  <form action="{% url 'movies:delete' movie.pk review.pk%}" method='POST'>
    {% csrf_token %}
    <button>삭제</button>
  </form>
  <a href="{% url 'movies:movie_detail' movie.pk %}">BACK</a>

  {% comment %} Comments {% endcomment %}

<div class="container my-4">
  <div class="ui form">
    <div class="field">
      <label class="text-light">댓글 남기기</label>
       <form action="{% url 'movies:comments_create' movie.pk review.pk %}" method ='POST'> 
            {% csrf_token %}
            {{ comment_form.as_p }}
            <div>
              <button class="ui blue labeled submit icon button" type="submit"> 
              <i class="icon edit" ></i>Write Comment </button> 
            </div>
        </form>
    </div>
  </div>
</div>
   <p>{{ comments|length }}개의 댓글이 있습니다.</p>
  <div class="container">
  <table class="ui celled striped table">
    <thead>
      <tr><th colspan="3">
        Comments
      </th>
    </tr></thead>
    <tbody>
      <tr>
      {% for comment in comments %}
        <td>
          <a class="ui image label" href="{% url 'accounts:profile' comment.user_id%}">
          {% if comment.user.gender == '불특정' %}
            <img src= {% static 'images/smile.jpg' %}>
            {{ comment.user }}
          {% elif comment.user.gender == '남'  %}
            <img src= {% static 'images/man1.png' %}>
            {{ recommentview.user }}
          {% elif comment.user.gender == '여'  %}
            <img src= {% static 'images/woman3.png' %}>
            {{ comment.user }}
          {% endif %}
        </a> 
        <a href=" {% url 'movies:detail' movie.pk comment.pk  %}"> {{ comment.title }} </a>
        </td>
        <td> {{ comment.content }}</td>
        <td class="right aligned">{{ comment.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

movies/templates/movies/update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container my-4">
  <div class="ui form">
    <div class="field">
      <label class="text-light">Update Review</label>
       <form action="" method ='POST'> 
          {% csrf_token %}
          {{ form.as_p }}
          <div>
            <button class="ui blue labeled submit icon button" type="submit"> 
            <i class="icon edit" ></i>Update Review </button> 
          </div>
        </form>
    </div>
  </div>
</div>

{% endblock content %}