SMSM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('maps/', include('maps.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    # path('delete/', views.delete, name='delete'),
    # path('update/', views.update, name='update'),
    # path('password/', views.change_password, name='change_password'),
    path('<int:user_pk>/', views.profile, name='profile'),
    # path('<int:user_pk>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views

app_name="movies"
urlpatterns = [
    # 전체 영화 목록
    path('', views.movie_index, name='movie_index'),
    # 영화 상세 페이지
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),

    # Review create
    path('<int:movie_pk>/create/', views.create, name='create'),
    # Review detail
    path('<int:movie_pk>/detail/<int:review_pk>', views.detail, name='detail'),
    # Review delete
    path('<int:movie_pk>/delete/<int:review_pk>', views.delete, name='delete'),
    # Review update
    path('<int:movie_pk>/update/<int:review_pk>', views.update, name='update'),
   
    # Comment create
    path('<int:movie_pk>/<int:review_pk>/comments/create', views.comments_create, name='comments_create'),
    # # Comment delete
    # path('<int:movie_pk>/<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    # # Review likes
    # path('<int:review_pk>/likes/', views.likes, name='likes'),
    # path('recommend/', views.recommend, name='recommend'),

]

SMSM/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  {% comment %} semantic UI CDN {% endcomment %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <!-- Site Properties -->
  <title>Homepage</title>
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/site.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/container.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/image.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/menu.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/divider.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/dropdown.css' %}">  
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/segment.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/button.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/icon.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/sidebar.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/transition.css' %}">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
  {% comment %} <link rel="stylesheet" type="text/css" href="semantic/dist/semantic.min.css"> {% endcomment %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
  <div class="ui container">
    <a class="active item">Home</a>
    <a class="item">Work</a>
    <a class="item">Company</a>
    <a class="item">Careers</a>
    <div class="right menu">
      <div class="item">
        <a class="ui button">Log in</a>
      </div>
      <div class="item">
        <a class="ui primary button">Sign Up</a>
      </div>
    </div>
  </div>
</div>

<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  <a class="active item">Home</a>
  <a class="item">Share Moments</a>
  <a class="item">Share Movie</a>
  <a class="item">Careers</a>
  <a class="item">Login</a>
  <a class="item">Signup</a>
</div>


<!-- Page Contents -->
<div class="pusher">
  <div class="ui inverted vertical masthead center aligned segment">

    <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
        <div class="left item">
            <img class="ui small image"src="{% static 'images/둥이로고.png' %}" alt="">
        </div>
        <a class="active item" href="{% url 'movies:movie_index' %}">Home</a>
        <a class="item">Share Moments</a>
        <a class="item">Share Movie</a>
        <a class="item">Careers</a>
        {% if request.user.is_authenticated %}
          <div class="right item">
            <a class="ui inverted button" href="{% url 'accounts:profile' user.pk %}">My Page</a>
            <form action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <button class="ui inverted button">Logout</button>
            </form>
          </div>
        {% else %}
          <div class="right item">
            <a class="ui inverted button" href="{% url 'accounts:login' %}">Log in</a>
            <a class="ui inverted button" href="{% url 'accounts:signup' %}">Sign Up</a>
          </div>
        {% endif %}
      </div>
    </div>

    
{% block content %}{% endblock content %}



  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">About</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">화정</a>
            <a href="#" class="item">서윤</a>
            {% comment %} <a href="#" class="item">Religious Ceremonies</a>
            <a href="#" class="item">Gazebo Plans</a> {% endcomment %}
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Services</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">AAA</a>
            <a href="#" class="item">BBB</a>
            {% comment %} <a href="#" class="item">How To Access</a>
            <a href="#" class="item">Favorite X-Men</a> {% endcomment %}
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Footer Header</h4>
          {% comment %} <p>Extra space for a call to action inside the footer that could help re-engage users.</p> {% endcomment %}
        </div>
      </div>
    </div>
  </div>
</div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
  {% comment %} <script src="assets/library/jquery.min.js"></script> {% endcomment %}
  <script>
  $(document)
    .ready(function() {


      $('.masthead')
        .visibility({
          once: false,
          onBottomPassed: function() {
            $('.fixed.menu').transition('fade in');
          },
          onBottomPassedReverse: function() {
            $('.fixed.menu').transition('fade out');
          }
        })
      ;

      // create sidebar and attach to menu open
      $('.ui.sidebar')
        .sidebar('attach events', '.toc.item')
      ;

    })
  ;
  </script>
  <script src="{% static 'dist/components/visibility.js' %}"></script>
  <script src="{% static 'dist/components/sidebar.js' %}"></script>
  <script src="{% static 'dist/components/transition.js' %}"></script> 
  <script src="http://semantic-ui.com/javascript/library/jquery.min.js"></script>
  <script src="http://semantic-ui.com/javascript/library/history.js"></script>
  <script src="http://semantic-ui.com/javascript/library/easing.js"></script>
  <script src="http://semantic-ui.com/javascript/library/ace/ace.js"></script>
  <script src="http://semantic-ui.com/javascript/library/tablesort.js"></script>
  <script src="http://semantic-ui.com/javascript/library/waypoints.js"></script>
  <script src="http://semantic-ui.com/build/packaged/javascript/semantic.min.js"></script>
  <script src="http://semantic-ui.com/javascript/semantic.js"></script>
  <script>
  {% block js %}{% endblock js %}
</body>

</html>